### ISSUE TITLE
Error using the reader, not a feed

### ISSUE THREAD

**Issue by faolisilva** [medikoo/google-group-reader#1]
Hello @medikoo  this is still working? I can't make it work, I am receiving the following error:

Error: Not a feed
    at FeedParser.handleEnd (/mnt/d/Donwloads/google-group-reader/node_modules/feedparser/main.js:129:13)
    at SAXStream.emit (events.js:198:13)
    at SAXParser.SAXStream._parser.onend (/mnt/d/Donwloads/google-group-reader/node_modules/sax/lib/sax.js:184:8)
    at emit (/mnt/d/Donwloads/google-group-reader/node_modules/sax/lib/sax.js:615:33)
    at end (/mnt/d/Donwloads/google-group-reader/node_modules/sax/lib/sax.js:654:3)
    at SAXParser.end (/mnt/d/Donwloads/google-group-reader/node_modules/sax/lib/sax.js:149:24)
    at SAXStream.end (/mnt/d/Donwloads/google-group-reader/node_modules/sax/lib/sax.js:234:16)
    at FeedParser._flush (/mnt/d/Donwloads/google-group-reader/node_modules/feedparser/main.js:1010:15)
    at FeedParser.prefinish (_stream_transform.js:141:10)
    at FeedParser.emit (events.js:198:13)
    at prefinish (_stream_writable.js:635:14)
    at finishMaybe (_stream_writable.js:643:5)
    at endWritable (_stream_writable.js:663:3)
    at FeedParser.Writable.end (_stream_writable.js:594:5)
    at Request.onend (internal/streams/legacy.js:42:10)
    at Request.emit (events.js:203:15)
    at IncomingMessage.<anonymous> (/mnt/d/Donwloads/google-group-reader/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by medikoo** [comment]
@faolisilva Yes, it should work. Still it works only for public groups. Is the group you're trying to observe public?
